services:
  media-control-center:
    build: .
    container_name: media-control-center

    ports:
      - "3002:3000"
    env_file:
      - .env.local
    extra_hosts:
      - "host.docker.internal:host-gateway"

    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: media-cloudflared
    restart: unless-stopped
    command: tunnel run
    volumes:
      - ./cloudflared:/etc/cloudflared
    extra_hosts:
      - "host.docker.internal:host-gateway"
